#!/usr/bin/env node
/**
 * Consolidate multi-page guides into single-page guides.
 *
 * Each multi-page guide lives in a directory with an index.md and several
 * sibling chapter files. This script folds each sibling into the index as
 * an H2 section (headings demoted, imports hoisted, relative sibling
 * links rewritten to anchors) and collects redirects so old chapter URLs
 * land on the right anchor on the consolidated page.
 *
 * Usage:
 *   node scripts/consolidate-guides.mjs --dry-run    # print plan only
 *   node scripts/consolidate-guides.mjs              # rewrite files
 *   node scripts/consolidate-guides.mjs --only=dotnet,ruby  # subset
 */
import fs from "node:fs";
import path from "node:path";
import yaml from "js-yaml";

const ARGS = process.argv.slice(2);
const DRY = ARGS.includes("--dry-run");
const ONLY = (ARGS.find((a) => a.startsWith("--only=")) ?? "")
  .replace("--only=", "")
  .split(",")
  .filter(Boolean);

const REPO = path.resolve(new URL("..", import.meta.url).pathname);
const GUIDES = path.join(REPO, "src/content/docs/guides");
const REDIRECTS_FILE = path.join(REPO, "src/data/redirects-migration.json");

/* ── Utilities ──────────────────────────────────────── */

function slugify(s) {
  return String(s)
    .toLowerCase()
    .replace(/[’'"`]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function parseFile(p) {
  const raw = fs.readFileSync(p, "utf8");
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return { fm: {}, body: raw };
  return { fm: yaml.load(m[1]) ?? {}, body: m[2] };
}

function splitFences(body) {
  const lines = body.split("\n");
  const out = [];
  let inFence = false;
  let marker = "";
  for (const line of lines) {
    const m = line.match(/^(`{3,}|~{3,})/);
    if (m) {
      if (!inFence) {
        inFence = true;
        marker = m[1][0].repeat(m[1].length);
      } else if (line.startsWith(marker)) {
        inFence = false;
      }
      out.push({ line, inFence: true });
    } else {
      out.push({ line, inFence });
    }
  }
  return out;
}

function demoteHeadings(body) {
  return splitFences(body)
    .map(({ line, inFence }) => {
      if (inFence) return line;
      const h = line.match(/^(#{1,5}) (.+)$/);
      return h ? "#" + h[1] + " " + h[2] : line;
    })
    .join("\n");
}

function extractImports(body) {
  const imports = [];
  const rest = [];
  for (const { line, inFence } of splitFences(body)) {
    if (
      !inFence &&
      /^import\s+[^'"]+from\s+['"][^'"]+['"];?\s*$/.test(line.trim())
    ) {
      imports.push(line.trim());
    } else {
      rest.push(line);
    }
  }
  return { imports, body: rest.join("\n") };
}

function rewriteSiblingLinks(body, siblingMap) {
  // siblingMap: filename-slug -> anchor-slug
  // Handles: ](slug/), ](./slug/), ](slug), with optional trailing anchor.
  return body.replace(
    /\]\((\.\/)?([a-z0-9][a-z0-9-]*)\/?(#[a-z0-9-]*)?\)/gi,
    (match, dot, slug, anchor) => {
      if (!(slug in siblingMap)) return match;
      return `](#${anchor ? anchor.slice(1) : siblingMap[slug]})`;
    },
  );
}

function buildHeading(label) {
  // Use a plain ATX H2. Starlight's TOC reads the markdown AST and ignores
  // raw HTML, so the on-this-page panel only picks up `## Label`. The
  // heading id is auto-generated by rehype-slug from the heading text,
  // which matches slugify(label) — that's what we use as the redirect
  // target anchor.
  return `## ${label}`;
}

/* ── Discovery ──────────────────────────────────────── */

function listMdFiles(dir) {
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isFile() && /\.mdx?$/.test(e.name))
    .map((e) => e.name);
}

function isMultiPageGuide(dir) {
  const files = listMdFiles(dir);
  if (files.length < 2) return false;
  return files.includes("index.md") || files.includes("index.mdx");
}

function discover() {
  const out = [];
  for (const e of fs.readdirSync(GUIDES, { withFileTypes: true })) {
    if (!e.isDirectory()) continue;
    const top = path.join(GUIDES, e.name);
    if (isMultiPageGuide(top)) out.push(top);
    for (const sub of fs.readdirSync(top, { withFileTypes: true })) {
      if (!sub.isDirectory()) continue;
      const nested = path.join(top, sub.name);
      if (isMultiPageGuide(nested)) out.push(nested);
    }
  }
  return out;
}

/* ── Consolidate one guide ──────────────────────────── */

function consolidate(dir) {
  const rel = path.relative(GUIDES, dir);
  const files = listMdFiles(dir);
  const indexName = files.includes("index.mdx") ? "index.mdx" : "index.md";
  const indexPath = path.join(dir, indexName);
  const index = parseFile(indexPath);

  const siblings = files
    .filter((f) => f !== indexName)
    .map((name) => {
      const full = path.join(dir, name);
      const parsed = parseFile(full);
      const slug = name.replace(/\.mdx?$/, "");
      const fm = parsed.fm ?? {};
      const order =
        typeof fm?.sidebar?.order === "number"
          ? fm.sidebar.order
          : Number.MAX_SAFE_INTEGER;
      const label = fm?.sidebar?.label ?? fm?.title ?? slug;
      return { name, full, slug, order, label, fm, body: parsed.body };
    })
    .sort((a, b) => a.order - b.order || a.name.localeCompare(b.name));

  const siblingMap = Object.fromEntries(
    siblings.map((s) => [s.slug, slugify(s.label)]),
  );

  const importSet = new Set();
  const sections = [];

  // Process the index body too — it may contain MDX imports and relative
  // links to chapters.
  {
    const { imports, body } = extractImports(index.body);
    imports.forEach((l) => importSet.add(l));
    sections.push(rewriteSiblingLinks(body, siblingMap).trimEnd());
  }

  for (const s of siblings) {
    const { imports, body: noImports } = extractImports(s.body);
    imports.forEach((l) => importSet.add(l));
    const demoted = demoteHeadings(noImports);
    const rewritten = rewriteSiblingLinks(demoted, siblingMap);
    const heading = buildHeading(s.label);
    sections.push(`\n${heading}\n\n${rewritten.trim()}\n`);
  }

  const hasMdx =
    indexName === "index.mdx" ||
    siblings.some((s) => s.name.endsWith(".mdx")) ||
    importSet.size > 0;

  const outName = hasMdx ? "index.mdx" : "index.md";
  const fmOut = { ...index.fm };
  const fmYaml = yaml
    .dump(fmOut, { lineWidth: 1000, noRefs: true, quotingType: '"' })
    .trimEnd();

  const importsBlock =
    importSet.size > 0 ? "\n" + [...importSet].join("\n") + "\n" : "";

  const finalBody = `---\n${fmYaml}\n---\n${importsBlock}\n${sections.join("\n")}\n`;

  const redirects = siblings.map((s) => ({
    from: `/guides/${rel}/${s.slug}/`,
    to: `/guides/${rel}/#${slugify(s.label)}`,
  }));

  return {
    dir,
    rel,
    indexPath,
    outName,
    outPath: path.join(dir, outName),
    body: finalBody,
    siblings,
    redirects,
  };
}

/* ── Main ───────────────────────────────────────────── */

function main() {
  const dirs = discover().filter((d) => {
    if (ONLY.length === 0) return true;
    const rel = path.relative(GUIDES, d);
    return ONLY.some((o) => rel === o || rel.startsWith(o + "/"));
  });

  console.log(`Found ${dirs.length} multi-page guide(s)${DRY ? " (dry run)" : ""}`);

  const allRedirects = [];
  for (const dir of dirs) {
    const plan = consolidate(dir);
    console.log(
      `\n• ${plan.rel}  (${plan.siblings.length} → 1${plan.outName === "index.mdx" ? ", mdx" : ""})`,
    );
    for (const s of plan.siblings) {
      console.log(`    ↳ ${s.name}  →  #${slugify(s.label)}`);
    }
    allRedirects.push(...plan.redirects);

    if (DRY) continue;

    // Write consolidated index (may change extension).
    fs.writeFileSync(plan.outPath, plan.body, "utf8");
    if (plan.outPath !== plan.indexPath) fs.unlinkSync(plan.indexPath);

    // Delete siblings.
    for (const s of plan.siblings) fs.unlinkSync(s.full);
  }

  if (!DRY && allRedirects.length > 0) {
    const existing = JSON.parse(fs.readFileSync(REDIRECTS_FILE, "utf8"));
    const seen = new Set(existing.map((r) => r.from));
    for (const r of allRedirects) {
      if (!seen.has(r.from)) {
        existing.push(r);
        seen.add(r.from);
      }
    }
    fs.writeFileSync(
      REDIRECTS_FILE,
      JSON.stringify(existing, null, 2) + "\n",
      "utf8",
    );
    console.log(`\nAppended ${allRedirects.length} redirect(s) to ${path.relative(REPO, REDIRECTS_FILE)}`);
  }

  console.log(`\nDone.`);
}

main();
